### ISSUE TITLE
Need help with the error

### ISSUE THREAD

**Issue by bagajohny** [ijanos/justwatchdumper#1]
I am getting the following error when I run the code

![image](https://github.com/ijanos/justwatchdumper/assets/101859073/f2648843-1be9-486f-9989-ca3e200adba0)

Here is what I did:
1. I loaded the page till the bottom to show the entire list.
2. I opened the console and copy pasted all the oneliners given in the readme
3. I clicked on "Run" to execute the commands

What is it that I am doing wrong? Please help.

**Comment by ijanos** [comment]
Oh, sorry, those steps are not clear, I should have updated the README. Some of the oneliners are for me to remember thing I tried. 

 you only need this one 

```js
output = []; document.querySelectorAll("h2.title-card-heading").forEach((e) => output.push(e.parentNode.href))
```

then just enter the variable name and copy and paste the list into a text file.  
```
output
```

<img width="712" alt="SCR-20231213-kofg" src="https://github.com/ijanos/justwatchdumper/assets/175447/a6ac13a7-7a20-4728-a0ce-0260764702ba">

also note that the copied object will have to be edited slightly for `curl` to understand. 

But I'd like to warn you, that the code in this repository is not a fully featured tool. I hacked it together until it worked for me to save my watchlist to a file and I stopped working on it after that. It can be a good starting point for you but you will need to understand what it is doing.

**Comment by bagajohny** [comment]
> Oh, sorry, those steps are not clear, I should have updated the README. Some of the oneliners are for me to remember thing I tried.
> 
> you only need this one
> 
> ```js
> output = []; document.querySelectorAll("h2.title-card-heading").forEach((e) => output.push(e.parentNode.href))
> ```
> 
> then just enter the variable name and copy and paste the list into a text file.
> 
> ```
> output
> ```
> 
> <img alt="SCR-20231213-kofg" width="712" src="https://private-user-images.githubusercontent.com/175447/290160977-a6ac13a7-7a20-4728-a0ce-0260764702ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODk4NzAsIm5iZiI6MTcwMjQ4OTU3MCwicGF0aCI6Ii8xNzU0NDcvMjkwMTYwOTc3LWE2YWMxM2E3LTdhMjAtNDcyOC1hMGNlLTAyNjA3NjQ3MDJiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNzQ2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTg5NDdhMWYzNGE4ODAxMzA2NjIzMDk5MGYzMmNjNGNiZWRkM2MyM2U4ZGRkNThlNWUwZTk5ZDcxMWU3NjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fA1du9JSW2sh83dPT8GI1Wym6NXm77-XXqSNC7m2m3M">
> 
> also note that the copied object will have to be edited slightly for `curl` to understand.
> 
> But I'd like to warn you, that the code in this repository is not a fully featured tool. I hacked it together until it worked for me to save my watchlist to a file and I stopped working on it after that. It can be a good starting point for you but you will need to understand what it is doing.

Why am I not getting the output with links just like you? Sorry i dont understand programming or what the code is actually doing. I am just trying to follow the instructions to get my watchlist.
![image](https://github.com/ijanos/justwatchdumper/assets/101859073/cbaeea43-0b5a-46af-bb65-4b5c6beb1cc7)
